### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [northworld/google_calendar#101]
Hi Northworld team, greatly appreciated your google_calendar gem 👍 

Is there any method to CRUD the Google Drive attachments that can be added to a Google Calendar events accounting to the Google Calendar API?

Many thanks,

Arnold

**Comment by szich** [comment]
Hi @arnoldmarunda, 

Google does provide the ability to work with attachments in their API.  See: https://developers.google.com/google-apps/calendar/v3/reference/events/insert

As you know, our library doesn't  currently support it.  If you would like to implement it, we would gladly accept the pull request.

**Our Feature Addition Policy**
The Northworld team has added all of the functionality we require in-house.  So we don't typically add additional features.  But we gladly accept all pull request that increases our coverage of the official API and meet our coding guidelines.

Best

Steve
