### ISSUE TITLE
Signet::AuthorizationError -- invalid_user

### ISSUE THREAD

**Issue by chiperific** [northworld/google_calendar#102]
I'm in the deep end here.

I set this:
`cal = Google::Calendar.new( client_id: ##, client_secret: ##, calendar: ##, redirect_url: "urn:ietf:wg:oauth:2.0:oob")`

Then I call this:
`cal.login_with_refresh_token(ENV['GCAL_REFRESH_TOKEN'])`

And I get `Google::HTTPAuthorizationFailed`

So, like a good little novice, I start tracking the code. I find the `Connection#initialize` block and see the `Signet::OAuth2::Client.new()`

I replicate that in the console:
`client = Signet::OAuth2::Client.new( client_id: '##.apps.googleusercontent.com', client_secret: '##', redirect_uri: "urn:ietf:wg:oauth:2.0:oob", refresh_token: '##', authorization_uri: "https://accounts.google.com/o/oauth2/auth", token_credential_uri: "https://accounts.google.com/o/oauth2/token", scope: "https://www.googleapis.com/auth/calendar", grant_type: "refresh_token")`

Then I try `client.fetch_access_token!` and get:
`Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error" : "invalid_user"
}`

I see my client object does have `client.username` and `client.password`, but not where this app would set those fields. Am I missing something?

**Comment by szich** [comment]
Hi @chiperific, usually when this happens it's because the entered credentials don't have access to the google calendar API on Google's end.  Take a look at the instructions in the Readme file.  Many people also find it useful to run the sample code, also in the Readme file.
