### ISSUE TITLE
Accessing a calendar's time zone

### ISSUE THREAD

**Issue by smilansky** [northworld/google_calendar#39]
Does the wrapper currently persist the timezone of the calendar? I wasnt able to find it anywhere.

From the api documentation:

{
  "kind": "calendar#calendar",
  "etag": etag,
  "id": string,
  "summary": string,
  "description": string,
  "location": string,
  "timeZone": string
}

**Comment by alexagranov** [comment]
Support for "timeZone" via `time_zone` attribute was added in 74033679df8aa96e09fa9ec2d0ca6fb92c66d0bb
