### ISSUE TITLE
Multi-user use case

### ISSUE THREAD

**Issue by bfosberry** [northworld/google_calendar#55]
I'm trying to use this to either have a different calendar for each user (requires creation of calendar support as well as calendar id reading support) OR have each users profile create events on a shared calendar. With the second option, I am guessing the user should never need to connect their google account, as all auth can be done through a service account's refresh token. 

I like the idea of using the users auth to login but I don't think that would fit with using the shared calendar approach.

What's the recommended approach?

**Comment by szich** [comment]
Hi @bfosberry, this is not really a issue, but I'll do my best to help you.  In general, I would do what is ever going to make your end users happiest.  

The google_calender gem will work fine with both situations.

In the first situation (different calendars) each end user will need to approve access to their calendar (if they have one) and you will need to store their refresh token (and check to see if it was revoked).  If you want everyone to see all of the events then you will need to aggregate them and manage keeping them in sync (this would be hard).  If you want everyone's events to stay private, this is the way to go.

In the shared calendar situation, you would manage the calendar and your end users would never need to approve access (it would just work).  Also, if everyone should see all the events, they you are all set.  If  however, the events should remain private, you will have a management headache.

Hope this helps.
