### ISSUE TITLE
Attributes not writable

### ISSUE THREAD

**Issue by tomav** [northworld/google_calendar#61]
Hi,

Thanks for this gem, very nice work.
I juste notices that some attributes are said being writable on  https://developers.google.com/google-apps/calendar/v3/reference/events/insert#examples like the "id" but only readable in your library.

    attr_reader :id, :raw, :html_link, :status

I got a: 

    /data/calendar.rb:51:in `block in <main>': undefined method `id=' for #<Google::Event:0x000000020a2dd0> (NoMethodError)
      from /usr/local/rvm/gems/ruby-2.1.5/gems/google_calendar-0.4.4/lib/google/calendar.rb:263:in `setup_event'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/google_calendar-0.4.4/lib/google/calendar.rb:180:in `create_event'
      from /data/calendar.rb:45:in `<main>'

Is there a particular reason?

Thank you.

**Comment by szich** [comment]
No, we wrote just enough of a wrapper to get the library working for our in house use.  You are welcome to submit a pull request that adds the functionality you would like.

**Comment by tomav** [comment]
That's what I thought.
Thank you.
