### ISSUE TITLE
Is Version 0.5 gem out of sync with github?

### ISSUE THREAD

**Issue by mrjcleaver** [northworld/google_calendar#82]
My Ruby runtime and IDE say there is no method =find_events_by_extended_properties_in_range=

On inspection I see:

![google_calendar 2015-10-04 10-48-11](https://cloud.githubusercontent.com/assets/59202/10268405/7cb738da-6a85-11e5-9c5f-6df8f01ec235.png)

````
 gem which google_calendar
/Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/google_calendar-0.5/lib/google_calendar.rb
````

Is the gem source out of sync?

Thanks,
   Martin.

**Comment by mrjcleaver** [comment]
The answer, according to https://rubygems.org/gems/google_calendar is that the gem has not been updated since Nov 2014.

**Comment by mrjcleaver** [comment]
Looks like https://github.com/rdp/specific_install is a workaround.

**Comment by szich** [comment]
Wow, how time flies, he sheepishly said.  It has been a while and there have been quite a few additions.  I'll push a new version shortly.

**Comment by szich** [comment]
The date on the last push was wrong... it was actually released last May.  I went ahead a published a new version anyway.

**Comment by mrjcleaver** [comment]
Thanks Steve!
