### ISSUE TITLE
calendars.clear always returns "Cannot clear primary calendar."

### ISSUE THREAD

**Issue by ChristopherHodge** [northworld/google_calendar#84]
client.execute!(:api_method => calendar_api.calendars.clear,
                        :parameters => { :calendarId => id }
                       )

Always returns:

/opt/ruby2.2.3/lib/ruby/gems/2.2.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:662:in `block (2 levels) in execute!': Cannot clear primary calendar. (Google::APIClient::ClientError)

Despite 'id' being a secondary calendar.

**Comment by szich** [comment]
This google_calendar gem does not offer a clear method.  I think you submitted this to the wrong library.
