### ISSUE TITLE
Zone conversion bug

### ISSUE THREAD

**Issue by t56k** [northworld/google_calendar#96]
I've run into a bug whereby my results from a `find_future_events` call gets the right `@raw` data in response, but the start time conversion to an attribute ignores or does something weird with the zone:

```
@raw=
    ...
    "start"=>
     {"dateTime"=>"2017-04-24T10:00:00-04:00", "timeZone"=>"America/New_York"},
    ...
@start_time=2017-04-24 14:00:00 UTC
```

I'm happy to submit a pull request to fix it but I thought I'd mention it here first in case it's something I'm missing.

**Comment by cd-rum** [comment]
And yeah, my zone is `America/New_York`, so the result time should be 10am.

**Comment by szich** [comment]
It would be much appreciated if you could track this down and submit a pull request.

**Comment by cd-rum** [comment]
Done, although I don't know if this breaks anything for anyone else obviously.
