### ISSUE TITLE
Missing rest of CRUD operations for calendar

### ISSUE THREAD

**Issue by harfangk** [northworld/google_calendar#98]
I noticed that this library lacks methods to handle calendar resource. It provides `create`, but nothing else. I added rudimentary `update`, `get`, and `delete` methods for calendar resource.

Currently the implementation lacks tests. I also think the library needs error handling for authorization (access to particular calendar resource or event resource), since authorization is critical for `update` and `delete` operations.

**Comment by szich** [comment]
Addressed in #99
